AWSTemplateFormatVersion: 2010-09-09

Resources:
  rDylanUser:
    Type: AWS::IAM::User
    Properties:
      Policies: 
        - PolicyName: AllowS3Upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::athenas3cq2022/*"
      UserName: Dylan@deviant.com
  
  rEc2RoleAccess:
    Type: AWS::IAM::Role
    Properties: 
      Description: This role should allow access for the EC2 instance to communicate with pS3BucketName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      RoleName: EternalsEC2Access

  rRootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref rEc2RoleAccess
