#!/usr/bin/env python

import random

quotes = ["Avengers assemble!",
          "I am Iron Man.",
          "I am Inevitable.",
          "He may have been your father, boy, but he wasn't your daddy.",
          "I love you 3000.",
          "Everyone fails at who they are supposed to be, Thor. The measure of a person, of a hero...is how well they succeed at being who they are.",
          "But a thing isn't beautiful because it lasts. It's a privilege to be among them.",
          "On your left.",
          "We are groot.",
          "I can't control your fear, I can only control mine.",
          "I can do this all day.",
          "No man can win every battle, but no man should fall without a struggle.",
          "What did it cost? Everything.",
          "I'm Mary Poppins y'all!",
          "That's my secret, I'm always angry.",
          "Don't waste it. Don't waste your life.",
          "He's a friend from work!",
          "Vengeance has consumed you. It's consuming them. I'm done letting it consume me.",
          "Mr. Stark, I Don't Feel So Good.",
          "I Am Groot.",
          "You shouldn't have killed my mom and squished my Walkman.",
          "I had him on the ropes.",
          "In times of crisis, the wise build bridges while the foolish build barriers.",
          "You think life takes more than it gives, but not today. Today it's giving us something. It is giving us a chance.",
          "It's alright, you could never hurt me. I just feel you.",
          "Well let me know if real power wants a magazine or something.",
          "I can feel the righteousness surging!",
          "We're in the endgame now.",
          "Let me go. It's okay.",
          "I have nothing to prove to you.",
          "I do anything and everything that Mr. Stark requires-including occasionally taking out the trash.",
          "Genius. Billionaire. Playboy. Philanthropist.",
          "When you said you would take me to California for the first time, I thought you meant Coachella or Disneyland.",
          "I'll get you all the cheeseburgers you want.",
          "I'm made of rocks, as you can see. But don't let that intimidate you. You don't need to be afraid unless you're made of scissors. Just a little rock-paper-scissor joke for you.",
          "I think you look great, Cap. As far as I'm concerned, that's America's ___.",
          "If you're nothing without this suit, then you shouldn't have it.",
          "I'll explain when you're older, Hawkeye.",
          "What is this thing? Look how it thinks it's so cool. It's not cool to get help. Walk by yourself you little gargoyle.",
          "Puny god.",
          "You're The Spiderling. Crime-Fighting Spider. You're Spider-Boy?",
          "It's an honor to meet you, officially. I sort of met you, I mean, I watched you while you were sleeping.",
          "I thought you were smaller.",
          "Can't have a revolution without somebody to overthrow, so you're welcome, and uh, it's a tie.",
          "His name is Redwing. He's cute. Go ahead, pet him.",
          "Boom! You looking for this?",
          "This is the fight of our lives, and we're going to win. Whatever it takes.",
          "You get hurt, hurt 'em back. You get killed, walk it off.",
          "Is he, though?",
          "I thought that you could sense that with your Peter Tingle",
          "'Boh' is my new superpower. It's like the anti-Aloha. I was born to say this word.",
          "You're repeating yourself! You're repeating yourself!",
          "The price of freedom is high, it always has been. And it's a price I'm willing to pay. And if I'm the only one, then so be it. But I'm willing to bet I'm not.",
          "I was already slipping when you happened to punch me in the face. The two events are not related.",
          "Then again that's the hero gig, part of the journey is the end.",
          "Whatever happens tomorrow you must promise me one thing, that you will stay who you are. Not a perfect soldier but a good man.",
          "The hardest choices require the strongest wills.",
          "Let me tell you. That kid's not even here yet and, there's nothing I wouldn't do for him.",
          "Don't do anything I would do, and don't do anything I wouldn't do. There's a little gray area in there. That's where you operate.",
          "This is your chance. To earn that look in your daughter's eyes. To become the hero that she already thinks you are. It's not about saving our world, it's about saving theirs. ",
          "You call me 'young lady' again, I'll shove my foot up somewhere it's not supposed to be.",
          "I'm not sure you understand the concept of a getaway car.",
          "I think we must learn from our mistakes and do better. You must not give up hope.",
          "I beat some guys up. Saved the dog. Some light B and E",
          "Sorry, I tend to process traumatic events with dad jokes.",
          "We got the full clown car. It means whatever the threat is, S.W.O.R.D clearly has no idea what they are dealing with.",
          "Sacrifice? That would imply I had something to lose.",
          "I can't believe you were D.B. cooper! Come on!",
          "She was literally one split end from cutting her own bangs.",
          "I made macaroni if you want some.",
          "You, Vision, are the piece of the mind stone that lives in me, you are a body of wires, and blood, and bone that I created. You are my sadness and my hope. But mostly, you're my love."
]


print(random.choice(quotes))